'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference.EquipmentFileServiceSoap")>  _
    Public Interface EquipmentFileServiceSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetFileByteStreamFromDC", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetFileByteStreamFromDC(ByVal FilePath As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetFileFromDC", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetFileFromDC(ByVal EventDate As String, ByVal ShopAbb As String, ByVal TargetType As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetFileInfoFromDC", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetFileInfoFromDC(ByVal EventDate As String, ByVal ShopAbb As String, ByVal TargetType As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetListFileInfoFromDC", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetListFileInfoFromDC(ByVal EventDate As String, ByVal ShopAbb As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateTransferStatus", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function UpdateTransferStatus(ByVal FileScheduleID As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ErrorMessage", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function ErrorMessage() As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface EquipmentFileServiceSoapChannel
        Inherits ServiceReference.EquipmentFileServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class EquipmentFileServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference.EquipmentFileServiceSoap)
        Implements ServiceReference.EquipmentFileServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetFileByteStreamFromDC(ByVal FilePath As String) As System.Data.DataTable Implements ServiceReference.EquipmentFileServiceSoap.GetFileByteStreamFromDC
            Return MyBase.Channel.GetFileByteStreamFromDC(FilePath)
        End Function
        
        Public Function GetFileFromDC(ByVal EventDate As String, ByVal ShopAbb As String, ByVal TargetType As String) As System.Data.DataTable Implements ServiceReference.EquipmentFileServiceSoap.GetFileFromDC
            Return MyBase.Channel.GetFileFromDC(EventDate, ShopAbb, TargetType)
        End Function
        
        Public Function GetFileInfoFromDC(ByVal EventDate As String, ByVal ShopAbb As String, ByVal TargetType As String) As System.Data.DataTable Implements ServiceReference.EquipmentFileServiceSoap.GetFileInfoFromDC
            Return MyBase.Channel.GetFileInfoFromDC(EventDate, ShopAbb, TargetType)
        End Function
        
        Public Function GetListFileInfoFromDC(ByVal EventDate As String, ByVal ShopAbb As String) As System.Data.DataTable Implements ServiceReference.EquipmentFileServiceSoap.GetListFileInfoFromDC
            Return MyBase.Channel.GetListFileInfoFromDC(EventDate, ShopAbb)
        End Function
        
        Public Function UpdateTransferStatus(ByVal FileScheduleID As String) As Boolean Implements ServiceReference.EquipmentFileServiceSoap.UpdateTransferStatus
            Return MyBase.Channel.UpdateTransferStatus(FileScheduleID)
        End Function
        
        Public Function ErrorMessage() As String Implements ServiceReference.EquipmentFileServiceSoap.ErrorMessage
            Return MyBase.Channel.ErrorMessage
        End Function
    End Class
End Namespace
